### ISSUE TITLE
bad name (change it to Boxel)

### ISSUE THREAD

**Issue by ZeroTixDev** [Counterproduction-game/Counterproduction#40]
also why can't i pull request, add me as contributor

**Comment by iMplode-nZ** [comment]
@ZeroTixDev stfu, and don't make me block you

**Comment by ZeroTixDev** [comment]
> 
> 
> @ZeroTixDev stfu, and don't make me block you

what do you think about boxel and add me as contributor (why would you block me? im helping you avoid choosing a bad name)

**Comment by iMplode-nZ** [comment]
@ZeroTixDev First, discord. Second, I'm not going to add you as contributor until you understand how to code in Rust at least a decent amount, as otherwise the only thing you could "help" with is screwing up my code.

**Comment by iMplode-nZ** [comment]
(Boxel still doesn't tell anything about what the game is)

**Comment by bychtromae** [comment]
> > @ZeroTixDev stfu, and don't make me block you
> 
> what do you think about boxel and add me as contributor (why would you block me? im helping you avoid choosing a bad name)

boxel is so much of a worse name lol, it tells literally nothing about the game while counterproduction tells so much more. the game is about fighting (the counter part) and production (using factories or whatever to produce goods) or something like that. PLUS THE GAME HAS NOTHING TO DO WITH VOXELS SO WHY WOULD YOU WANT TO NAME IT BOXEL

**Comment by bychtromae** [comment]
like you might as well have just chosen a name at complete random

**Comment by bychtromae** [comment]
or is that what you did? lol

**Comment by ZeroTixDev** [comment]
> 
> 
> > > @ZeroTixDev stfu, and don't make me block you
> > 
> > 
> > what do you think about boxel and add me as contributor (why would you block me? im helping you avoid choosing a bad name)
> 
> boxel is so much of a worse name lol, it tells literally nothing about the game while counterproduction tells so much more. the game is about fighting (the counter part) and production (using factories or whatever to produce goods) or something like that. PLUS THE GAME HAS NOTHING TO DO WITH VOXELS SO WHY WOULD YOU WANT TO NAME IT BOXEL

fine then lets name it ``Faxel``,

**Comment by ZeroTixDev** [comment]
> 
> 
> @ZeroTixDev First, discord. Second, I'm not going to add you as contributor until you understand how to code in Rust at least a decent amount, as otherwise the only thing you could "help" with is screwing up my code.

ok ok im learning rust but i can still help point out small issues that can be fixed (not screwing up your code necessarily _-_)

**Comment by bychtromae** [comment]
> > @ZeroTixDev First, discord. Second, I'm not going to add you as contributor until you understand how to code in Rust at least a decent amount, as otherwise the only thing you could "help" with is screwing up my code.
> 
> ok ok im learning rust but i can still help point out small issues that can be fixed (not screwing up your code necessarily _-_)

Knowing you, you will definitely screw up their code.

> > > > @ZeroTixDev stfu, and don't make me block you
> > > 
> > > 
> > > what do you think about boxel and add me as contributor (why would you block me? im helping you avoid choosing a bad name)
> > 
> > 
> > boxel is so much of a worse name lol, it tells literally nothing about the game while counterproduction tells so much more. the game is about fighting (the counter part) and production (using factories or whatever to produce goods) or something like that. PLUS THE GAME HAS NOTHING TO DO WITH VOXELS SO WHY WOULD YOU WANT TO NAME IT BOXEL
> 
> fine then lets name it `Faxel`, also the game name doesn't have to corellate to the game idea and i think faxel is good name too.

are you just joking at this point are you actually being serious

**Comment by haha0201** [comment]
Knowing ZeroTix, he is going to mess up your code on purpose. Even if he knows what Rust is, he will mess it up.
I remember sharing my multiplayer game with him. I added him as a contributor, the next thing you know, he did Ctrl A and backspace. Good thing I saved a zip file.
And Zero, you can't even deny this. You said it was just a troll, but clearly there were malicious intents. You never put it back, even after me telling you to for 1 minute before removing your contributor and restoring.

**Comment by haha0201** [comment]
Secondly, it can be really clear here that Zero really does not care about helping the game. He spends no time thinking about a good name and instead attempts to protect the name that he chose which is absolutely terrible and has nothing to do with the game and also is extremely cringe. All he is attempting to do here is help the game enough that he gets contributor and then he can do nothing and then brag about how he coded the game.
Don't fall into his trap.

**Comment by iMplode-nZ** [comment]
@haha0201 Well I'm not going to allow people to change history, but I'm fine with people making pull requests.
(I think contrubitor is about accepting prs)
