### ISSUE TITLE
bevy-orbit-controls license

### ISSUE THREAD

**Issue by jakobhellermann** [Counterproduction-game/Counterproduction#44]
Would you be opposed to making the `bevy-orbit-controls` crate a more permissive license like MIT?
I wanted to use the source code as an inspiration for my own camera system, but don't necessarily want to make my own code GPL.

**Comment by iMplode-nZ** [comment]
I think `bevy-orbit-controls` is licensed ISC, but that's only in the `Cargo.toml` thing. I'm not quite sure whether that counts, if it doesn't I'll move it to a separate repo.

**Comment by jakobhellermann** [comment]
Oh right, I was looking for a LICENSE.md file and only found the one in the repository root. Thanks for the clarification!
